Use cookie if localStorage is not available (for safari in incognito mode)
radyushin/vue-localstorage pull request #6
Opened 2017-08-22 11:01 UTC by ElForastero

Added cookie micro-framework by MDN. It's similar to localStorage object and has almost the same methods.

Removed rollup and gulp form dependencies.

Built with babel.

If localStorage is not available cookie will be used.

2017-08-22 13:13 UTC, pbelyaev commented
@ElForastero Tests are broken :(

2017-08-23 12:49 UTC, ElForastero commented
@pbelyaev Fixed. 👍

2017-08-23 13:36 UTC, pbelyaev requested changes
Rebuild the dist file and we're okay.

2017-08-23 13:36 UTC, pbelyaev commented on dist/index.js
> +    // });
Why is this commented out?

2017-08-24 05:20 UTC, ElForastero commented
@pbelyaev Done!

2017-08-24 05:29 UTC, pbelyaev approved these changes

2017-08-24 05:29 UTC, merged